service:
  parsers_file: ${FLUENTBIT_HOME}/conf/parsers.conf
  flush: 1

pipeline:
  inputs:
    - name:  tail
      path: ./nginx.json.log
      parser: json
      read_from_head: true
      tag: nginx-feed

  filters:
    - name:  checklist
      ignore_case: false
      mode: partial
      file: ./fluentbit/ip-checklist.data
      print_query_time: false
      record: known_origin yes
      match: nginx-feed
      lookup_key: remote_ip

    - name:  record_modifier
      uuid_key: myUUID
      record: hostname ${HOSTNAME}
      match: nginx-feed

    - name:  modify
      condition: key_exists known_origin
      set: identifiedValue matched
      rename: remote_user user
      match: nginx-feed
      remove: agent referrer request

  outputs:
    - name:  stdout
      match: "*"

