service:
  flush_interval: 1

pipeline:
  inputs:
    - name: tail
      path: ./chapter3/structured-rolling-log.0.log
      db: ./chapter3/rotating-file-read.db
      db.locking: false
      refresh_interval: 15
      rotate_wait: 10
      ignore_older: false
      read_from_head: true
      tag: rotating-file-read

  outputs:
    - name: stdout
      match: "*"
