service:
  flush_interval: 1
  log_level: error

pipeline:
  inputs:
    - name: http
  tag: http-in
  listen: 0.0.0.0
  port: 9881

  outputs:
    - name: stdout
      match: "*"
      json_date_key: received-date
      json_date_format: iso8601
      format: json_lines

    - name: file
      match: "*"
      file: output1.csv
      format: csv
      delimiter: \t

    - name: file
      match: "*"
      file: output1.ltsv
      format: ltsv
      label_delimiter: comma
      delimiter: comma

    - name: file
      match: "*"
      file: output1.txt
      format: plain

    - name: file
      match: "*"
      file: output1.msgpack
      format: msgpack

    - name: file
      match: "*"
      format: template
      file: output1.templated.txt
      template: addressing={hello} value={val} --- {time}
