service:
  flush_interval: 5
  daemon: Off
  log_level: info
  parsers_file: parsers.conf
  plugins_file: plugins.conf
  HTTP_server: Off
  HTTP_listen: 0.0.0.0
  HTTP_port: 2020

pipeline:
  inputs:
    - name: random
      tag: db.random
      interval_sec: 5

  filters:
    - name: modify
      match: db.random
      add:
        - a_string "record n"
        - a_number 9876
        - a_dtg "2024-01-26 21:17:47.943048332"
        - a_decimal 10000000.0001
      rename: rand_value a_key

  outputs:
    - name: out_gdb
      match: db.random
      db_host: 192.168.1.135
      db_port: 3306
      db_user: demo
      db_password: demo
      ordering_col: a_key
      table_name: pluginsrc
      db_name: demo
      db_type: mysql
      pk: a_key
      log_level: debug

    - name: stdout
      match: "*"
